name: Build and Deploy to K8s

on:
  push:
    branches: [ main ]

env:
  REGISTRY_NAME: mcpartlandhomekit
  IMAGE_NAME: movieclubceo
  IMAGE_TAG: ${{ github.sha }}
  RESOURCE_GROUP: homekit

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image to ACR
        run: |
          az acr login --name ${{ env.REGISTRY_NAME }}
          docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}