name: Build and deploy .NET application to container app mrmovieclubceo-app-2025040509015
on:
  push:
    branches:
    - main
env:
  CONTAINER_APP_CONTAINER_NAME: mrmovieclubceo
  CONTAINER_APP_NAME: mrmovieclubceo-app-2025040509015
  CONTAINER_APP_RESOURCE_GROUP_NAME: mrmovieclubceo
  CONTAINER_REGISTRY_LOGIN_SERVER: mrmovieclubceo.azurecr.io
  DOCKER_FILE_PATH: MrMovieClubCEO/Dockerfile
  PROJECT_NAME_FOR_DOCKER: mrmovieclubceo
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.mrmovieclubceo_USERNAME_74A3 }}
        password: ${{ secrets.mrmovieclubceo_PASSWORD_74A3 }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.mrmovieclubceo_app_2025040509015_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v2
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.mrmovieclubceo_USERNAME_74A3 }} --password ${{ secrets.mrmovieclubceo_PASSWORD_74A3 }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
